### ISSUE TITLE
CRUD actions for the /orders resource

### ISSUE THREAD

**Issue by MatthewChiappa** [NYU-DevOps-S17/Orders#10]
**As a** user of the REST API
**I need** basic create, read, update, and delete on the resource
**So that** I can perform actions to modify orders

**Assumptions:**
* The resource CRUD actions should follow correct REST API guidelines

**Acceptance Criteria:**
```
Given I want to access the /orders resource
When I attempt to create, read, update, and delete orders
Then the service should correctly preform these actions
```

**Comment by JudeRuben** [comment]
Hey may i know who is working on this issue??I have assigned it to myself.is that okay?

**Comment by MatthewChiappa** [comment]
@JudeRuben this is the entire epic that holds the CRUD action issue attached to it. theres no work on this its just a placeholder that ties all of those stories together

**Comment by JudeRuben** [comment]
@MatthewChiappa : ya i know it.thanks!!
