### ISSUE TITLE
Add Persistence to the REST api

### ISSUE THREAD

**Issue by MatthewChiappa** [NYU-DevOps-S17/Orders#17]
**As a** api user of the orders resource
**I need** a way to keep information about the orders I modify
**So that** I can shut down and turn on the server

**Assumptions:**
* The data I change in the database should remain when I start the server again

**Acceptance Criteria:**
```
Given I change or create an order
When I shut down the server
Then the order should be changed or in the database when I turn it back on
```

**Comment by sdytjkgala** [comment]
Fetch the latest repo and do a vagrant up. It should get Redis ready for you. And you can start developing the persistence feature using all the Redis package. Example is "server.py"(sample code from professor)
