### ISSUE TITLE
Add a database to the vagrantfile

### ISSUE THREAD

**Issue by MatthewChiappa** [NYU-DevOps-S17/Orders#18]
**As a** api user of the orders resource
**I need** a way to keep information about the orders I modify
**So that** I can shut down and turn on the server

**Assumptions:**
* The database should work with the Vagrantfile

**Acceptance Criteria:**
```
Given I change or create an order
When I shut down the server
Then the order should be changed or in the database when I turn it back on
```

**Comment by sdytjkgala** [comment]
This has been added as I setup #19
