### ISSUE TITLE
Add a unit test to test for our duplicate action

### ISSUE THREAD

**Issue by MatthewChiappa** [NYU-DevOps-S17/Orders#31]
**As a** API user
**I need** to test the orders resource
**So that** I can test for the duplicate action

**Acceptance Criteria:**
```
Given I run the test suite
When I want to test the duplicate functionality
Then I should have a test that covers this scenario
```

**Comment by sdytjkgala** [comment]
Hey @MaskyYoung , we may still need to fix the code for "duplicate" action first
