### ISSUE TITLE
Add behave test to cover duplicate action

### ISSUE THREAD

**Issue by MatthewChiappa** [NYU-DevOps-S17/Orders#33]
**As a** API user
**I need** to test the orders resource
**So that** I can test for the duplicate action

**Acceptance Criteria:**
```
Given I run the test suite
When I want to test the duplicate functionality
Then I should have a test that covers this scenario
```

**Comment by sdytjkgala** [comment]
Hey @MatthewChiappa , we may still need to fix the code for "duplicate" action
